version: "3"

services:
  web:
    container_name: weather_web
    build:
      context: .
      dockerfile: dockerfile
    ports:
     - "8081:8080"
    volumes:
      - .:/opt
#    entrypoint: python /opt/src/weather.py
    links:
      - mongo
    depends_on:
      - mongo
    networks:
    - public

  mongo:
    image: mongo:latest
    container_name: mongo-weather
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    networks:
    - public

networks:
  public:
    external: true
